In [105]:
import numpy as np
from sklearn import preprocessing
import csv
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, f1_score
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier

# Here is the file path to give

# This is cleaning data converting into matrices form 
# Here stripped of whitespaces and converted into lower case |



with open("C:/Users/rishi/OneDrive/Desktop/Task2.csv",encoding='utf-8') as file:
  reader = csv.reader(file, delimiter=',')
  next(reader)
  count = 0
  set1 = set()
  X_tmp =[]
  y_tmp =[]
  for line in reader:
    y1 =[]
    X_tmp.append(line[0].lower().strip())
    count = count +1
    #new = line[1].split("|")
    #print(new)
    y1.append(line[1].lower().strip())
    set1.add(line[1].lower().strip())
    if line[2] != '':
      y1.append(line[2].lower().strip())
    
    y_tmp.append(y1)

    #if count == 10:
      #break

print("X_Samples = ",len(X_tmp))
print("y_Samples = ",len(y_tmp))

#print(len(y_tmp))

print(f"Labels ={set1}")
print("count_labels=", len(set1))

print(y_tmp)

X_Samples =  1000
y_Samples =  1000
Labels ={'connect', 'other', 'iot', 'govt data', 'cyber', 'public', 'agri', 'edu', 'utility', 'mobility', 'deit', 'sustain'}
count_labels= 12
[['edu', 'other'], ['connect', 'other'], ['edu', 'other'], ['deit', 'other'], ['mobility', 'other'], ['deit', 'edu'], ['connect', 'other'], ['connect', 'iot'], ['connect', 'other'], ['mobility', 'other'], ['other', 'other'], ['edu', 'other'], ['mobility', 'other'], ['mobility', 'other'], ['mobility', 'other'], ['utility', 'connect'], ['deit', 'other'], ['deit', 'other'], ['public', 'other'], ['public', 'deit'], ['other', 'other'], ['deit', 'connect'], ['govt data', 'other'], ['deit', 'other'], ['connect', 'other'], ['sustain', 'other'], ['deit', 'cyber'], ['deit', 'public'], ['edu', 'public'], ['public', 'other'], ['connect', 'other'], ['public', 'other'], ['connect', 'other'], ['deit', 'other'], ['deit', 'other'], ['public', 'other'], ['deit', 'other'], ['other', 'other'], ['connect', 'other'], ['deit', 'other

In [106]:
X_txt_train, X_txt_test, y_train_text, y_test_text = train_test_split(X_tmp, y_tmp, test_size=0.2, random_state=42)

# converting into numpy arrays

X_train = np.array(X_txt_train)
X_test = np.array(X_txt_test)

In [107]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import precision_score, recall_score, f1_score
import sklearn.metrics
from sklearn.multioutput import MultiOutputClassifier

lb = preprocessing.MultiLabelBinarizer(classes=('connect', 'other', 'iot', 'govt data', 'cyber', 'public', 'agri', 'edu', 'utility', 'mobility', 'deit', 'sustain'))
y_train = lb.fit_transform(y_train_text)
y_test = lb.transform(y_test_text)
#print(y_test)
print(y_train.shape)
print(y_test.shape)
LogReg_pipeline = Pipeline([('vectorizer', CountVectorizer()),
('tfidf', TfidfTransformer()),
                ('clf', OneVsRestClassifier(LogisticRegression()))])
LogReg_pipeline.fit(X_train, y_train)
predicted = LogReg_pipeline.predict(X_test)



print(predicted)


print("Accuracy Score: ",accuracy_score(y_test, predicted))


precision = precision_score(predicted,y_test,average="macro") 
recall = recall_score(predicted,y_test,average="macro")
f1 = f1_score(y_test,predicted, average="macro")


f1 = f1_score(y_test,predicted, average="macro")
print("Precision: {:.4f}".format(precision))
print("Recall: {:.4f}".format(recall))
print("F1: {:.4f}".format(f1))


(800, 12)
(200, 12)
[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]
Accuracy Score:  0.075
Precision: 0.0905
Recall: 0.1340
F1: 0.0858


C:\Users\rishi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [108]:
# OneVsRestClassifier(LinearSVC()) with tf-idf vectorizer
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer

lb = preprocessing.MultiLabelBinarizer(classes=('connect', 'other', 'iot', 'govt data', 'cyber', 'public', 'agri', 'edu', 'utility', 'mobility', 'deit', 'sustain'))
y_train = lb.fit_transform(y_train_text)
y_test = lb.transform(y_test_text)

#print(y_test)
print(y_train.shape)
print(y_test.shape)

classifier = Pipeline([
('vec2', TfidfVectorizer(analyzer='word' , stop_words='english')),
('tfidf', TfidfTransformer()),
('clf', OneVsRestClassifier(LinearSVC()))])

classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)
#print(predicted)
print("Accuracy Score: ",accuracy_score(y_test, predicted))
precision = precision_score(predicted,y_test,average="macro") # Get scores using svm_test_predictions and y_test with the precision_score method
recall = recall_score(predicted,y_test,average="macro")
f1 = f1_score(predicted,y_test,average="macro")
print("Precision: {:.4f}".format(precision))
print("Recall: {:.4f}".format(recall))
print("F1: {:.4f}".format(f1))

(800, 12)
(200, 12)
Accuracy Score:  0.135
Precision: 0.1556
Recall: 0.3122
F1: 0.1869


C:\Users\rishi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [109]:
# Linear svc with countvectorizer & ngramrange(1,2) 
from sklearn.metrics import precision_score, recall_score, f1_score

lb = preprocessing.MultiLabelBinarizer(classes=('connect', 'other', 'iot', 'govt data', 'cyber', 'public', 'agri', 'edu', 'utility', 'mobility', 'deit', 'sustain'))
y_train = lb.fit_transform(y_train_text)
y_test = lb.transform(y_test_text)
print(y_test)

#print(y_test)
print(y_train.shape)
print(y_test.shape)

classifier = Pipeline([
('vectorizer', CountVectorizer()),
('tfidf', TfidfTransformer()),
('clf', OneVsRestClassifier(LinearSVC()))])

classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)
print(predicted)
print("Accuracy Score: ",accuracy_score(y_test, predicted))
precision = precision_score(predicted,y_test,average="macro") # Get scores using svm_test_predictions and y_test with the precision_score method
recall = recall_score(predicted,y_test,average="macro")
f1 = f1_score(predicted,y_test,average="macro")
print("Precision: {:.4f}".format(precision))
print("Recall: {:.4f}".format(recall))
print("F1: {:.4f}".format(f1))

[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 1 ... 1 0 0]
 [0 1 0 ... 0 0 0]]
(800, 12)
(200, 12)
[[0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 [0 1 0 ... 0 0 0]]
Accuracy Score:  0.145
Precision: 0.1635
Recall: 0.3409
F1: 0.2011


C:\Users\rishi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [112]:
num_comments = 0
num_tweets = 0
for text, pred  in zip(X_tmp, predicted):
    print("Comment: {}".format(text))
    print("Prediction: {}".format(pred))
    print()
    num_tweets += 1
    if num_tweets == 200:
        break

Comment: adding typing to my resume is not a bad idea, i will take that, and i am still in highschool, if i don't find a job before i graduate that can carry me through college, im most definitely scooping up a computer lab job at vista lol
Prediction: [1 0 0 0 0 0 0 0 0 0 0 0]

Comment: my time warner tech told me they are doing upgrades to gigabit speed in august if that helps...
Prediction: [1 0 0 0 0 0 0 0 0 0 0 0]

Comment: the thing to keep in mind is that we are amateurs, me (bass) has never played in front of people ever and i am teaching myself how to play with a computer program. one of the guys that came one week was someone that plays in another band and we felt really lacking compared to him.
Prediction: [1 0 0 0 0 0 0 0 0 0 0 0]

Comment: try club 12 on san pedro.  good area,on bus line, just what you have been searching for. (https://www.google.com/search?q=club12+san+antonio&amp;ie=utf-8&amp;oe=utf-8&amp;hl=en-us&amp;client=safari)
Prediction: [1 0 0 0 0 0 0 0 0 0 0 0]


In [113]:
# OneVsRestClassifier(LinearSVC()))  with tf-idf vectorizer with n gram range (1,3)
from sklearn.metrics import precision_score, recall_score, f1_score

lb = preprocessing.MultiLabelBinarizer(classes=('other', 'iot', 'mobility', 'connect', 'edu', 'util', 'public', 'ag', 'cyber', 'govt data', 'enviro', 'dei'))
y_train = lb.fit_transform(y_train_text)
y_test = lb.transform(y_test_text)

#print(y_test)
print(y_train.shape)
print(y_test.shape)

classifier = Pipeline([
('vectorizer', CountVectorizer(ngram_range=(1, 3))),
('tfidf', TfidfTransformer()),
('clf', OneVsRestClassifier(LinearSVC()))])

classifier.fit(X_train, y_train)
predicted = classifier.predict(X_test)
#print(predicted)
print("Accuracy Score: ",accuracy_score(y_test, predicted))
precision = precision_score(predicted,y_test,average="macro") # Get scores using svm_test_predictions and y_test with the precision_score method
recall = recall_score(predicted,y_test,average="macro")
f1 = f1_score(predicted,y_test,average="macro")
print("Precision: {:.4f}".format(precision))
print("Recall: {:.4f}".format(recall))
print("F1: {:.4f}".format(f1))

C:\Users\rishi\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:875: UserWarning: unknown class(es) ['agri', 'deit', 'sustain', 'utility'] will be ignored
  warnings.warn(


(800, 12)
(200, 12)
Accuracy Score:  0.215
Precision: 0.1299
Recall: 0.3334
F1: 0.1516


C:\Users\rishi\anaconda3\lib\site-packages\sklearn\multiclass.py:79: UserWarning: Label not 5 is present in all training examples.
  warnings.warn(
C:\Users\rishi\anaconda3\lib\site-packages\sklearn\multiclass.py:79: UserWarning: Label not 7 is present in all training examples.
  warnings.warn(
C:\Users\rishi\anaconda3\lib\site-packages\sklearn\multiclass.py:79: UserWarning: Label not 10 is present in all training examples.
  warnings.warn(
C:\Users\rishi\anaconda3\lib\site-packages\sklearn\multiclass.py:79: UserWarning: Label not 11 is present in all training examples.
  warnings.warn(
C:\Users\rishi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rishi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarni